In [1]:
import pandas as pd
import numpy as np
import math
import random

In [2]:
fruit = pd.read_csv("fruit.csv")

In [164]:
X = fruit[["width","height"]]
y = fruit["fruit"]
Y = y-1

In [165]:
print X.shape
print y.shape

(59, 2)
(59,)


In [230]:
class LogisticRegression:
    def __init__(self, eta, lambda_parameter):
        self.eta = eta
        self.lambda_parameter = lambda_parameter
    
    def oneHot(self, y, k=3):
        base = np.array([np.ones(len(y)),]*k).transpose()
        scale = np.array(range(1,k+1))
        comp = base*scale
        y_comp = np.array([np.array(y).transpose(),]*k).transpose()
        self.y_mat = 1*np.equal(y_comp,comp)
        return self.y_mat
    
    def softmax(self,mat,k):
        exps = np.exp(mat)
        denom = np.array([np.sum(exps,1), ]*k).transpose()
        return exps/denom

    # TODO: Implement this method!
    def fit(self, X, C):
        self.X = pd.DataFrame(X)
        self.C = pd.DataFrame(C)
        self.y = self.oneHot(self.C,3)
        
        n = self.X.shape[0]
        m = self.X.shape[1]
        k = 3
        num_iters = 100
        theta = np.zeros((m,k))
        mat = np.dot(X,theta)
        
        for i in range(num_iters):
            h = np.dot(X,theta) 
            probs = softmax(h,k)
            grad = (float(1)/m)*np.dot(X.transpose(),y_mat - probs)/len(X) + (self.lambda_parameter/m)*theta
            theta = theta - self.eta*grad
        
        return theta

    # TODO: Implement this method!
    def predict(self, X_to_predict):
        # The code in this method should be removed and replaced! We included it just so that the distribution code
        # is runnable and produces a (currently meaningless) visualization.
        
        h_pred = np.dot(X_to_predict,theta)
        pred_probs = softmax(h_pred,k)
        
        return np.argmax(pred_probs,axis=1)

In [235]:
logis = LogisticRegression(0.001,1000)
logis.oneHot(y,3)
logis.fit(X,y)
logis.predict(X)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [166]:
#One-hot encoding of y 
base = np.array([np.ones(len(fruit)),]*k).transpose()
scale = np.array(range(1,k+1))
comp = base*scale
y_comp = np.array([np.array(y).transpose(),]*k).transpose()
y_mat = 1*np.equal(y_comp,comp)

In [167]:
num_classes = 3
alpha = 0.001
lamb = 0
J = 0

n = X.shape[0]
m = X.shape[1]
k = num_classes
theta = np.zeros((m,k))
mat = np.dot(X,theta)

def softmax(mat,k):
    exps = np.exp(mat)
    denom = np.array([np.sum(exps,1), ]*k).transpose()
    return exps/denom

baseline = softmax(mat,k)

In [188]:
theta = np.zeros((m,k))
mat = np.dot(X,theta)

In [187]:
theta0 = np.zeros((m,k))
mat0 = np.dot(X,theta0)
baseline = softmax(mat0,k)
#print baseline
np.argmax(y_mat - baseline, axis=1)
print np.argmax(baseline-y_mat,axis=1)
print baseline-y_mat

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[[-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [-0.66666667  0.33333333  0.33333333]
 [ 0.33333333 -0.66666667  0.33333333]
 [ 0.33333333 -0.66666667  0.33333333]
 [ 0.33333333 -0.66666667  0.33333333]
 [ 0.33333333 -0.6666

In [222]:
num_classes = 3
alpha = 0.01
lamb = float(50)
J = 0

theta = np.zeros((m,k))
mat = np.dot(X,theta)

for i in range(30):
    mat = np.dot(X,theta) 
    probs = softmax(mat,k)
    grad = (float(1)/m)*np.dot(X.transpose(),y_mat - probs)/len(X) + (lamb/m)*theta
    print (lamb/m)*theta
    theta = theta - alpha*grad
    print theta
    
    

[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[-0.00016667 -0.00284463  0.0030113 ]
 [ 0.001      -0.00181356  0.00081356]]
[[-0.00416667 -0.07111582  0.07528249]
 [ 0.025      -0.04533898  0.02033898]]
[[-0.00021783 -0.0053839   0.00560173]
 [ 0.00183225 -0.00361583  0.00178358]]
[[-0.00544582 -0.13459744  0.14004327]
 [ 0.04580634 -0.09039581  0.04458947]]
[[-0.00019457 -0.00766129  0.00785586]
 [ 0.002525   -0.0053741   0.0028491 ]]
[[-0.00486426 -0.19153232  0.19639657]
 [ 0.06312509 -0.13435247  0.07122738]]
[[-0.0001273  -0.00971108  0.00983839]
 [ 0.00309991 -0.00706551  0.0039656 ]]
[[-0.00318261 -0.2427771   0.24595972]
 [ 0.07749782 -0.17663784  0.09914002]]
[[ -3.83225488e-05  -1.15607513e-02   1.15990739e-02]
 [  3.57386765e-03  -8.67481555e-03   5.10094790e-03]]
[[-0.00095806 -0.28901878  0.28997685]
 [ 0.08934669 -0.21687039  0.1275237 ]]
[[  5.63085013e-05  -1.32327682e-02   1.31764597e-02]
 [  3.96028881e-03  -1.01925437e-02   6.23225486e-03]]
[[ 0.00140771 -0.33081921  0.32941149]
 

In [223]:
#outs = np.equal(softie,np.amax(softie,axis=1))
print probs
np.argmax(probs,axis=1)

[[ 0.31535003  0.20810364  0.47654633]
 [ 0.3171418   0.21436594  0.46849226]
 [ 0.31848327  0.21621194  0.46530478]
 [ 0.31871987  0.21447223  0.46680791]
 [ 0.31869577  0.21754926  0.46375498]
 [ 0.31983617  0.21932218  0.46084165]
 [ 0.3189375   0.21580215  0.46526036]
 [ 0.31975154  0.21990985  0.46033861]
 [ 0.31823369  0.21363863  0.46812769]
 [ 0.31778136  0.21404492  0.46817371]
 [ 0.31770414  0.21462308  0.46767277]
 [ 0.31755776  0.2127213   0.46972095]
 [ 0.3177458   0.21280662  0.46944758]
 [ 0.31829614  0.21612616  0.4655777 ]
 [ 0.31848327  0.21621194  0.46530478]
 [ 0.31785793  0.21346787  0.4686742 ]
 [ 0.31826661  0.21487994  0.46685345]
 [ 0.31888254  0.2176352   0.46348226]
 [ 0.31709823  0.21009008  0.4728117 ]
 [ 0.32387726  0.24286295  0.43325978]
 [ 0.32442421  0.24519444  0.43038136]
 [ 0.32506978  0.2489882   0.42594202]
 [ 0.32483636  0.24817361  0.42699003]
 [ 0.32522841  0.25117305  0.42359855]
 [ 0.31058231  0.19051078  0.4989069 ]
 [ 0.31019591  0.19034643

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [27]:
theta

array([[ nan,  nan,  nan],
       [ nan,  nan,  nan]])

In [5]:
X = np.array(fruit[["width","height"]])

#TODO: One-Hot ENcode these y's
y = np.array(fruit["fruit"])


In [23]:
#init class #
num_classes = 3
alpha = 0.1
J = 0

n = X.shape[0]
m = X.shape[1]
k = num_classes
theta = np.zeros((m,k))
mat = np.dot(X,theta)

In [14]:
theta.shape

(2, 3)

In [7]:
base = np.array([np.ones(len(fruit)),]*k).transpose()
scale = np.array(range(1,k+1))
comp = base*scale
y_comp = np.array([np.array(y).transpose(),]*k).transpose()
#print y_comp

#THIS IS A ONE-HOT ENCODING OF THE ORIGINAL Y LABELS
one_hot = 1*np.equal(y_comp,comp)
one_hot

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0,

In [10]:
def softmax(mat,k):
    exps = np.exp(mat)
    denom = np.array([np.sum(exps,1), ]*k).transpose()
    return exps/denom

# want to compute the gradient of the loss
#def grad(mat,k):
 #   soft_grad = softmax(mat,k)*(1-softmax(mat,k))
#   return soft_grad



# now, update thetas depending on grad of loss?
def update(grad,theta,eta):
    updated = theta + eta*theta*grad # want this to be elementwise?

softie = softmax(mat,k)

In [13]:
softie

array([[ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.33333333],
       [ 0.33333333,  0.33333333,  0.333

In [25]:
error = np.absolute(softie - one_hot)
grad = np.matmul(X.transpose(),error)
new_theta = theta - alpha*grad
new_theta

array([[-18.69666667, -19.75      , -17.44666667],
       [-19.78      , -20.88666667, -19.85333333]])

In [19]:
#forward pass
#1. Matrix Mult
#2. Softmax trasfoooorm!

#backward pass
#1. Error compooping (softmax w/ "correct" of y subtracted)
#2. Compooping gradient (input' * error (from 1))
#2.5 Update grad

#Wepeeet!

In [9]:
#init class #
num_classes = 3

J = 0

n = X.shape[0]
m = X.shape[1]
k = num_classes
theta = np.zeros((m,k))
mat = np.dot(X,theta)

In [16]:
print X.shape
#print y.shape
#print mat.shape
print theta.shape
#print softie.shape
print error.shape

(59, 2)
(2, 3)
(59, 3)


In [45]:
new_theta = np.dot(X.transpose(),error)
new_theta

array([[ -1.96666667, -33.56666667,  35.53333333],
       [ 11.8       , -21.4       ,   9.6       ]])

In [37]:
def softmax(mat,k):
    exps = np.exp(mat)
    denom = np.array([np.sum(exps,1), ]*k).transpose()
    return exps/denom

# want to compute the gradient of the loss
#def grad(mat,k):
 #   soft_grad = softmax(mat,k)*(1-softmax(mat,k))
#   return soft_grad

# now, update thetas depending on grad of loss?
def update(grad,theta,eta):
    updated = theta + eta*theta*grad # want this to be elementwise?

softie = softmax(mat,k)

In [40]:
error = softie - one_hot
error

array([[-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [-0.66666667,  0.33333333,  0.33333333],
       [ 0.33333333, -0.66666667,  0.33333333],
       [ 0.33333333, -0.66666667,  0.333

In [16]:
mat = np.dot(X,theta)

h = sigmoid(np.dot(X,theta));
J = (1/m)*((-y)*log(h) - (1-y)'*log(1-h)) + lambda/(2*m) * theta(2:end)'*theta(2:end);
grad = (1/m) * X'*(h - y) + lambda/m * [0;theta(2:end)];

SyntaxError: invalid syntax (<ipython-input-16-b9f6237d0d44>, line 12)

In [12]:
X.shape[0]

(59, 2)